# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b65151d8f3605f7ebf5d075c1d88aa16aae2a98bb53ef43fb68832cd66090a1af51acf9c82bd8a0925de6b1c82be6c8207d990abf9d41860b0d774989468e5e

test:
  secret_key_base: 4830e4e6b0fb0fae58b44d900720d16e377ab66d8e6a26b4e5e39a8120989dc28916a6832bc6da0645211c9f51d513f2934612cd2d2ba5e09f4e8620c468941d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
